name: Twitter Alert Bot

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        with:
          path: state.json
          key: twitter-state-${{ github.run_id }}
          restore-keys: |
            twitter-state-

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run Bot
        run: python main.py
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TELEGRAM_BOT_TOKEN:   ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:     ${{ secrets.TELEGRAM_CHAT_ID }}
          TWITTER_USERNAMES:    ${{ secrets.TWITTER_USERNAMES }}
